### PR TITLE
Fix status bar updates getting lost

### PR DESCRIPTION
**Pull request by mrnugget**
This is super embarrassing, but ... well, here we are.

### CODE REVIEW

**Review by eseliger — APPROVED** [review]
OMG SO EMBARASSING

LGTM

**Comment by LawnGnome** [comment]
I don't think I understand why this makes a difference. Wasn't `numStatusBars` still in scope at the point the later check occurred anyway? :confused:

**Comment by mrnugget** [comment]
The `PrintStatuses` method is used as a callback and is called every ~second to print the current status.

The first time it's called, the progress bar and the status bars haven't been initialised, so the code behind `if p.progress == nil` is executed.

The second, third, ..., nth time it is called, the bars have been initialised, which means `if p.progress == nil` is _false_ and 🐛 the `numStatusBars` is stays `0` 🐛 .

**Comment by LawnGnome** [comment]
> The `PrintStatuses` method is used as a callback and is called every ~second to print the current status.

Aha! That was the bit of context I'd forgotten. Thanks for that!

**Pull request merged**
