### PR TITLE
codeintel: Update utils package; remove auth from redirect URL

### PR DESCRIPTION
**Pull request by efritz**

### CODE REVIEW

**Review by mrnugget — APPROVED** [review]
Does this need a CHANGELOG entry?

**Review by LawnGnome — APPROVED** [review]
I think a `go mod tidy` would get rid of a few dangling checksums in `go.sum` after the dependency update, but LGTM.

**Comment by efritz** [comment]
> Does this need a CHANGELOG entry?

Nah! This only affects auto-indexing and debugging.

**Comment by mrnugget** [comment]
> Nah! This only affects auto-indexing and debugging.

Then feel free to merge

**Pull request merged**
