### PR TITLE
spike: Multi workspace per repo

### PR DESCRIPTION
**Pull request by eseliger**

### CODE REVIEW

**Comment by mrnugget** [comment]
👍

**Comment by mrnugget** [comment]
(Removing myself as reviewer to clean up GitHub notifications. Feel free to re-add me if review is required)

**Comment by mrnugget** [comment]
Closing because PR seems to be stale. Feel free to re-open if needed.

**Comment by eseliger** [comment]
This is the base for the ticket in our P2 column to implement multi workspace support. I will reopen it, but it should be closed again once we implemented this. No review needed though.

**Pull request closed without merging**
