### PR TITLE
Remove duplication in templating helpers

### PR DESCRIPTION
**Pull request by mrnugget**
Noticed this while reading through the code.

### CODE REVIEW

**Review by eseliger — APPROVED** [review]
🧹

**Comment by mrnugget** [comment]
I'm ignoring the build issue since it's a known issue (https://github.com/sourcegraph/src-cli/issues/416) and go ahead with the merge (tests pass locally on my mac)

**Review by chrispine — COMMENTED** [review]
👍🏻

**Comment by LawnGnome** [comment]
Good catch!

**Pull request merged**
