### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by mucles**
relates to PR'S: https://github.com/sourcegraph/src-cli/pull/681 , https://github.com/sourcegraph/sourcegraph/pull/29991

### CODE REVIEW

**Comment by daxmc99** [comment]
@sourcegraph/batchers Just to confirm, there are no more steps needed after this. The CLI will be released as part of the next monthly release, correct?

**Review by eseliger — APPROVED** [review]
LGTM, in the future you can also include changelog entries in the PR itself, no need to take the effort and create a second one :)

**Comment by eseliger** [comment]
Yes, we sometimes release patch releases when necessary on our end, of if you tell us to, otherwise we will always cut a release close to the branch cut anyways.
Do you think this warrants a patch? It's relatively cheap and we can just tag it as 3.36.2 right away.

**Comment by mucles** [comment]
Yes, this would warrant a patch, Thank you @eseliger :), greatly appreciate your help 🙏 
cc: @mike-r-mclaughlin

**Pull request merged**
